---
title: "Covid-19 Report"
author: "Group 4"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r read-config}
config_list <- config::get(
    config = Sys.getenv("WHICH_CONFIG")
)
covid_enabled <- config_list$covid
if (covid_enabled == T) {
  check_covid = "covid"
} else {
  check_covid = "non-covid"
  }
print(paste0("Now we are analyzing ",check_covid , " data."))
```

```{r, set-chunk-opts, echo = FALSE, message = FALSE}
pacman::p_load(
  knitr,
  tree
  )
opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE
)
here::i_am("code/covid_report.Rmd")
```

```{r, print-organization-structure, include = F}
# setwd("D:/Yan/Emory/2024Fall/DATA550/DATA550-Midterm")
# 
# print_tree <- function(path, prefix = "") {
#   # list all files and folders
#   items <- list.files(path, full.names = TRUE)
# 
#   # calculate the max name to alige
#   max_length <- max(nchar(basename(items)))
# 
#   for (i in seq_along(items)) {
#     # print
#     if (i == length(items)) {
#       cat(prefix, "└── ", sprintf("%-*s", max_length, basename(items[i])), "\n")  # last
#       new_prefix <- paste0(prefix, "    ")  # update prefix
#     } else {
#       cat(prefix, "├── ", sprintf("%-*s", max_length, basename(items[i])), "\n")  # other
#       new_prefix <- paste0(prefix, " │   ")  # update prefix
#     }
# 
#     # check if folder
#     if (file.info(items[i])$isdir) {
#       print_tree(items[i], new_prefix)  # recursive call
#     }
#   }
# }
# print_tree(".")
```

## 01_demography
```{r}

```


## Part II - Case Severity and Health Outcomes Analysis
```{r}

```


## Part III - Association Analysis
```{r}

```


## Part IV - Temporal Trends and Outcome Analysis
```{r}

```

